/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bbn.tc.schema.avro.cdm13;
@SuppressWarnings("all")
/** * There are many types of sources such as sensors
     * The type of a sensor could be base (close to hardware) or composite
     * See https://source.android.com/devices/sensors/index.html for details
     * TODO: camera and GPS ideally should be modeled separately to match the Android model. These are rich subsystems */
@org.apache.avro.specific.AvroGenerated
public enum SrcSinkType {
  SOURCE_ACCELEROMETER, SOURCE_TEMPERATURE, SOURCE_GYROSCOPE, SOURCE_MAGNETIC_FIELD, SOURCE_HEART_RATE, SOURCE_LIGHT, SOURCE_PROXIMITY, SOURCE_PRESSURE, SOURCE_RELATIVE_HUMIDITY, SOURCE_LINEAR_ACCELERATION, SOURCE_MOTION, SOURCE_STEP_DETECTOR, SOURCE_STEP_COUNTER, SOURCE_TILT_DETECTOR, SOURCE_ROTATION_VECTOR, SOURCE_GRAVITY, SOURCE_GEOMAGNETIC_ROTATION_VECTOR, SOURCE_CAMERA, SOURCE_GPS, SOURCE_AUDIO, SOURCE_SYSTEM_PROPERTY, SOURCE_ENV_VARIABLE, SOURCE_SINK_IPC, SOURCE_UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SrcSinkType\",\"namespace\":\"com.bbn.tc.schema.avro.cdm13\",\"doc\":\"* There are many types of sources such as sensors\\n     * The type of a sensor could be base (close to hardware) or composite\\n     * See https://source.android.com/devices/sensors/index.html for details\\n     * TODO: camera and GPS ideally should be modeled separately to match the Android model. These are rich subsystems\",\"symbols\":[\"SOURCE_ACCELEROMETER\",\"SOURCE_TEMPERATURE\",\"SOURCE_GYROSCOPE\",\"SOURCE_MAGNETIC_FIELD\",\"SOURCE_HEART_RATE\",\"SOURCE_LIGHT\",\"SOURCE_PROXIMITY\",\"SOURCE_PRESSURE\",\"SOURCE_RELATIVE_HUMIDITY\",\"SOURCE_LINEAR_ACCELERATION\",\"SOURCE_MOTION\",\"SOURCE_STEP_DETECTOR\",\"SOURCE_STEP_COUNTER\",\"SOURCE_TILT_DETECTOR\",\"SOURCE_ROTATION_VECTOR\",\"SOURCE_GRAVITY\",\"SOURCE_GEOMAGNETIC_ROTATION_VECTOR\",\"SOURCE_CAMERA\",\"SOURCE_GPS\",\"SOURCE_AUDIO\",\"SOURCE_SYSTEM_PROPERTY\",\"SOURCE_ENV_VARIABLE\",\"SOURCE_SINK_IPC\",\"SOURCE_UNKNOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
