#! /usr/bin/env bash

LOG=/var/lib/aide/aide.db.log
DB=/var/lib/aide/aide.db
NEW=$DB.new
TODAY=$DB.`date +%Y-%m-%d`.gz
CFG=/etc/aide/aide.conf
CFG=/var/lib/aide/aide.conf.autogenerated
if [ `id -u` != 0 ]; then echo Please run as root: sudo $0; exit 1; fi
test -r $CFG || aideinit

sort_alpha() {
    env LC_ALL=C sort
}

mv ${LOG}{,~}  2> /dev/null
rm -f $OLD $NEW
aide --update --config $CFG  > $LOG
chmod g+r $NEW

(zcat < $NEW | sed -n 1,4p;
 zcat < $NEW | egrep -v '^# |^@@(begin_db$|end_db$|db_spec)' | sort_alpha;
 echo '@@end_db') |
 gzip > $TODAY
     
mv $NEW $DB
