resolver: lts-6.1
packages:
- '.'
- ../Ingest
- ../GremlinClient
- location: https://github.com/GaloisInc/avro/archive/master.zip
extra-deps:
- dotgen-0.4.2
- simple-get-opt-0.1.0.0
- milena-0.5.0.1
- uuid-1.3.11
- BoundedChan-1.0.3.0
- pure-zlib-0.4
- text-1.2.2.0
