/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bbn.tc.schema.avro.cdm18;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** * StartMarker records delineate system (re)starts in a data stream. */
@org.apache.avro.specific.AvroGenerated
public class StartMarker extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2591223611959633579L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"StartMarker\",\"namespace\":\"com.bbn.tc.schema.avro.cdm18\",\"doc\":\"* StartMarker records delineate system (re)starts in a data stream.\",\"fields\":[{\"name\":\"sessionNumber\",\"type\":\"int\",\"doc\":\"sequence number that monotonically increases each time the system is started\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** sequence number that monotonically increases each time the system is started */
  @Deprecated public int sessionNumber;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public StartMarker() {}

  /**
   * All-args constructor.
   * @param sessionNumber sequence number that monotonically increases each time the system is started
   */
  public StartMarker(java.lang.Integer sessionNumber) {
    this.sessionNumber = sessionNumber;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sessionNumber;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sessionNumber = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sessionNumber' field.
   * @return sequence number that monotonically increases each time the system is started
   */
  public java.lang.Integer getSessionNumber() {
    return sessionNumber;
  }

  /**
   * Sets the value of the 'sessionNumber' field.
   * sequence number that monotonically increases each time the system is started
   * @param value the value to set.
   */
  public void setSessionNumber(java.lang.Integer value) {
    this.sessionNumber = value;
  }

  /**
   * Creates a new StartMarker RecordBuilder.
   * @return A new StartMarker RecordBuilder
   */
  public static com.bbn.tc.schema.avro.cdm18.StartMarker.Builder newBuilder() {
    return new com.bbn.tc.schema.avro.cdm18.StartMarker.Builder();
  }

  /**
   * Creates a new StartMarker RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new StartMarker RecordBuilder
   */
  public static com.bbn.tc.schema.avro.cdm18.StartMarker.Builder newBuilder(com.bbn.tc.schema.avro.cdm18.StartMarker.Builder other) {
    return new com.bbn.tc.schema.avro.cdm18.StartMarker.Builder(other);
  }

  /**
   * Creates a new StartMarker RecordBuilder by copying an existing StartMarker instance.
   * @param other The existing instance to copy.
   * @return A new StartMarker RecordBuilder
   */
  public static com.bbn.tc.schema.avro.cdm18.StartMarker.Builder newBuilder(com.bbn.tc.schema.avro.cdm18.StartMarker other) {
    return new com.bbn.tc.schema.avro.cdm18.StartMarker.Builder(other);
  }

  /**
   * RecordBuilder for StartMarker instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<StartMarker>
    implements org.apache.avro.data.RecordBuilder<StartMarker> {

    /** sequence number that monotonically increases each time the system is started */
    private int sessionNumber;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.bbn.tc.schema.avro.cdm18.StartMarker.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sessionNumber)) {
        this.sessionNumber = data().deepCopy(fields()[0].schema(), other.sessionNumber);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing StartMarker instance
     * @param other The existing instance to copy.
     */
    private Builder(com.bbn.tc.schema.avro.cdm18.StartMarker other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.sessionNumber)) {
        this.sessionNumber = data().deepCopy(fields()[0].schema(), other.sessionNumber);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'sessionNumber' field.
      * sequence number that monotonically increases each time the system is started
      * @return The value.
      */
    public java.lang.Integer getSessionNumber() {
      return sessionNumber;
    }

    /**
      * Sets the value of the 'sessionNumber' field.
      * sequence number that monotonically increases each time the system is started
      * @param value The value of 'sessionNumber'.
      * @return This builder.
      */
    public com.bbn.tc.schema.avro.cdm18.StartMarker.Builder setSessionNumber(int value) {
      validate(fields()[0], value);
      this.sessionNumber = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sessionNumber' field has been set.
      * sequence number that monotonically increases each time the system is started
      * @return True if the 'sessionNumber' field has been set, false otherwise.
      */
    public boolean hasSessionNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sessionNumber' field.
      * sequence number that monotonically increases each time the system is started
      * @return This builder.
      */
    public com.bbn.tc.schema.avro.cdm18.StartMarker.Builder clearSessionNumber() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public StartMarker build() {
      try {
        StartMarker record = new StartMarker();
        record.sessionNumber = fieldSetFlags()[0] ? this.sessionNumber : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
