/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bbn.tc.schema.avro.cdm18;
@SuppressWarnings("all")
/** * TheiaQueryType used to indicate the type of TheiaQuery */
@org.apache.avro.specific.AvroGenerated
public enum TheiaQueryType {
  BACKWARD, FORWARD, POINT_TO_POINT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TheiaQueryType\",\"namespace\":\"com.bbn.tc.schema.avro.cdm18\",\"doc\":\"* TheiaQueryType used to indicate the type of TheiaQuery\",\"symbols\":[\"BACKWARD\",\"FORWARD\",\"POINT_TO_POINT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
