flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- dlist-0.7.1.2
- dotgen-0.4.2
- hashable-1.2.3.3
- monadLib-3.7.3
- mtl-2.2.1
- network-uri-2.6.0.3
- parsec-3.1.9
- syb-0.6
- text-1.2.1.3
- uniplate-1.6.12
- unordered-containers-0.2.5.1
- crypto-api-0.13.2
- monadcryptorandom-0.7.0
- cereal-0.5.1.0
- entropy-0.3.7
- tagged-0.8.3
resolver: ghc-7.10
