resolver: lts-7.2
packages:
- ../dashboard
- ../ingest/IngestDaemon
- ../ingest/Ingest
- location: https://github.com/GaloisInc/avro/archive/master.zip
- ../ingest/GremlinClient
- location: https://github.com/tylerholien/milena/archive/master.zip
extra-deps:
- dotgen-0.4.2
- simple-get-opt-0.1.0.0
- uuid-1.3.12
- BoundedChan-1.0.3.0
- pure-zlib-0.4
- text-1.2.2.0
flags: {}
extra-package-dbs: []
