# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"

  # Forward the Dashboard port for the user to get system status.
  config.vm.network "forwarded_port", guest: 8080, host: 8081

  # Provide a private network so we can allow other VMs to access Kafka.
  # Thi is done for our TA1 inputs (eventually it will  be replaced by
  # the tc-in-a-box kafka instance).
  config.vm.network "private_network", ip: "10.31.31.31"

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "4096"
     vb.cpus   = 2
  end

  config.vm.provision "file", source: "../dashboard", destination: "adapt/dashboard"
  config.vm.provision "file", source: "../ingest", destination: "adapt/ingest"
  config.vm.provision "file", source: "../config", destination: "adapt/config"
  config.vm.provision "file", source: "../example", destination: "adapt/example"
  config.vm.provision "shell", privileged: false, path: "bootstrap.sh"
  config.vm.provision "file", source: "start_daemons.sh", destination: "adapt/start_daemons.sh"
  config.vm.provision "file", source: "node_count.py", destination: "adapt/node_count.py"
end

