# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "2048"
     vb.cpus   = 2
  end

  config.vm.provision "file", source: "start_daemons.sh", destination: "start_daemons.sh"
  config.vm.provision "file", source: "../config/supervisord.conf", destination: "superisord.conf"
  config.vm.provision "file", source: "../ingest", destination: "ingest"
  config.vm.provision "shell", privileged: false, path: "bootstrap.sh"
end

